### PR TITLE
remove git diff and reformat

### PR DESCRIPTION
**Pull request by jarededwards**

### CODE REVIEW

**Comment by jarededwards** [comment]
hi @thenickdude, i was trying to work through this and get proxmox up and running on ec2 but was unsuccessful. after updating the cloud-init script to remove the git diff detail and fix the formatting the installation seems to complete, and i get the log output all the way to
```
------------------------------------------------------------------------------

Welcome to the Proxmox Virtual Environment. Please use your web browser to 
configure this server - connect to:

  https://<my-ip>:8006/

------------------------------------------------------------------------------
```
but so far have not been able to reach the UI over the public ip associated with the ec2 instance. If you have any further information that could help i'd love to know your thoughts. Im new to proxmox and was hoping to help a user in our open source community. looking forward to hearing from you. thanks in advance!

**Comment by thenickdude** [comment]
Networking is broken without this patch applied, you can't just remove it like this.

Which version of Proxmox are you testing?

**Comment by jarededwards** [comment]
thanks for letting me know, im using the `cloud-init.yaml` from this repo with no changes (noted the `hostname` and `fqdn` can be set up top) but the latest release 
https://github.com/thenickdude/proxmox-on-ec2/blob/master/cloud-init.yaml#L71-L72

**Comment by thenickdude** [comment]
Probably my patch doesn't apply on the latest version, I'll try it out and update it

**Comment by jarededwards** [comment]
hi again, im not sure what i did different this time around, but i just restarted the walk through and was able to successfully get on the box and get to the proxmox ui. the process to restart was to "reboot instance" in the ec2 ui this time

**Comment by thenickdude** [comment]
Yep, looks like the cloud-init script still works with the very latest version of Proxmox, it tested fine for me here too.

It's possible there was a race condition where the networking was restarted at the wrong instant

**Pull request closed without merging**
